LOGIN_FAIL = "User and/or password incorrect"
LOGIN_BLOCKED = "User is temporary blocked"
UNEXPECTED_ERROR = "An unexpected error occurred"
TODO_CREATED = "Item added successfully"
TODO_NOT_CREATED = "Item could not bet created"
TODO_DELETED = "Item deleted"
TODO_DELETE_FAIL = "Item could not be deleted"